{
    'name': 'Custom Sale ',
    'version': '18.0.1.0.0',
    'category': 'Sales',
    'summary': 'Custom Proforma Invoice Report for Sales Orders',
    'description': """Custom Proforma Invoice Report for Sales Orders, Purchase Orders, Invoices and Packing Lists""",
    'depends': ['sale', 'base', 'purchase', 'account', 'stock', 'product'],
    'data': [
        'views/sale_order_view.xml',
        'views/product_template_form.xml',
        'views/account_move_view.xml',
        'reports/sale_report.xml',
        'reports/sale_report_template.xml',
        'reports/purchase_report.xml',
        'reports/purchase_report_template.xml',
        'reports/invoice_report.xml',
        'reports/invoice_report_template.xml',
        'reports/packing_list_report.xml',
        'reports/packing_list_template.xml',
    ],
    'installable': True,
    'application': False,
    'license': 'LGPL-3',
}
